spring.application.name=table-service
server.port=8083
server.servlet.context-path=/table-service

#mysql db connection configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_tables
spring.datasource.username=root
spring.datasource.password=274123