spring.application.name=employee-service
server.port=8081

#mysql db connection configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_employee
spring.datasource.username=root
spring.datasource.password=274123