spring.application.name=ingredient-service
serever.port=8080

#mysql db connection configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_ingredients
spring.datasource.username=root
spring.datasource.password=274123